style = "blue"
# indent_type = "Spaces"
# indent_width = 4
# column_width = 92
# always_for_in = true
# whitespace_typedefs = false
# whitespace_ops_in_indices = true
# remove_extra_newlines = true
# import_to_using = false
# pipe_to_function_call = true
# short_to_long_function_def = false
# long_to_short_function_def = false
# always_use_return = false
